name: Build and push Build Linux Release docker images

on:
  # push:
  #   branches: [main]
  #   paths:
  #     - ".github/workflows/docker.yml"
  workflow_run:
    workflows: ["Build Linux Release Using docker"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        run: |
          echo VERSION=$(cat share/const.go  |grep 'const VERSION' | awk '{print $4}' | sed "s/\"//g")  >> $GITHUB_ENV

      - name: Check Version
        run: echo $VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Development
        uses: docker/build-push-action@v2
        with:
          context: ./docker/custom
          platforms: linux/amd64
          build-args: |
            VERSION=${{ env.VERSION }}
            ARCH=amd64
          push: true
          tags: wwsheng009/yao-amd64:latest

      - name: Build Development Arm64
        uses: docker/build-push-action@v2
        with:
          context: ./docker/custom
          platforms: linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }} 
            ARCH=arm64
          push: true
          tags: wwsheng009/yao-arm64:latest
